	server_name: Spoiled Milk World Builder Runtime
	server_bind_address: 127.0.0.1
	server_port: 43615
	ws_server_port: 43616
	client_version: 10046
	member_world: true
	based_map_data: 64
	want_myworld: true
	custom_landscape: true
	want_packet_register: false
