package orsc.remastered;

// Generated by tools/myworld/remastered-sprites/workspace.py. Do not edit by hand.
final class RemasteredSpriteCatalogData {
	static final String REVISION = "dfe0b76dc874196e7c2e1f6ce650bba3834634926554dd06a01fcf36e4cf32b3";
	static final Record[] ENTRIES = {
		new Record("sprite/items/0/0", "items/mace-entry-000/frames/00.png", 36, 23, true, 6, 4, 48, 32, "exact-canonical", "inherit", 128, "item-mace-entry-000", "thatkidbobo"),
		new Record("sprite/items/1/0", "items/short-sword-entry-001/frames/00.png", 41, 23, true, 4, 4, 48, 32, "exact-canonical", "inherit", 128, "item-short-sword-entry-001", "thatkidbobo"),
		new Record("sprite/items/103/0", "items/rope-entry-103/frames/00.png", 21, 26, true, 14, 3, 48, 32, "exact-canonical", "inherit", 128, "item-rope-entry-103", "thatkidbobo"),
		new Record("sprite/items/108/0", "items/banana-entry-108/frames/00.png", 31, 30, true, 9, 2, 48, 32, "exact-canonical", "inherit", 128, "item-banana-entry-108", "thatkidbobo"),
		new Record("sprite/items/109/0", "items/cooking-apple-entry-109/frames/00.png", 25, 29, true, 14, 3, 48, 32, "exact-canonical", "inherit", 128, "item-cooking-apple-entry-109", "thatkidbobo"),
		new Record("sprite/items/110/0", "items/pie-dish-entry-110/frames/00.png", 35, 22, true, 3, 7, 48, 32, "exact-canonical", "inherit", 128, "item-pie-dish-entry-110", "thatkidbobo"),
		new Record("sprite/items/111/0", "items/pie-shell-entry-111/frames/00.png", 36, 22, true, 2, 7, 48, 32, "exact-canonical", "inherit", 128, "item-pie-shell-entry-111", "thatkidbobo"),
		new Record("sprite/items/113/0", "items/half-pie-entry-113/frames/00.png", 36, 22, true, 8, 8, 48, 32, "exact-canonical", "inherit", 128, "item-half-pie-entry-113", "thatkidbobo"),
		new Record("sprite/items/114/0", "items/portrait-entry-114/frames/00.png", 23, 31, true, 3, 1, 48, 32, "exact-canonical", "inherit", 128, "item-portrait-entry-114", "thatkidbobo"),
		new Record("sprite/items/115/0", "items/excalibur-entry-115/frames/00.png", 41, 23, true, 6, 8, 48, 32, "exact-canonical", "inherit", 128, "item-excalibur-entry-115", "thatkidbobo"),
		new Record("sprite/items/116/0", "items/eye-and-fire-sword-entry-116/frames/00.png", 11, 11, true, 18, 14, 48, 32, "exact-canonical", "inherit", 128, "item-eye-and-fire-sword-entry-116", "thatkidbobo"),
		new Record("sprite/items/117/0", "items/rat-tail-entry-117/frames/00.png", 40, 10, true, 7, 19, 48, 32, "exact-canonical", "inherit", 128, "item-rat-tail-entry-117", "thatkidbobo"),
		new Record("sprite/items/118/0", "items/goblin-armour-entry-118/frames/00.png", 47, 27, true, 1, 5, 48, 32, "exact-canonical", "inherit", 128, "item-goblin-armour-entry-118", "thatkidbobo"),
		new Record("sprite/items/12/0", "items/hatchet-entry-012/frames/00.png", 41, 25, true, 3, 4, 48, 32, "exact-canonical", "inherit", 128, "item-hatchet-entry-012", "thatkidbobo"),
		new Record("sprite/items/125/0", "items/gemmed-amulet-entry-125/frames/00.png", 42, 23, true, 6, 7, 48, 32, "exact-canonical", "inherit", 128, "item-gemmed-amulet-entry-125", "thatkidbobo"),
		new Record("sprite/items/126/0", "items/amulet-and-superchisel-entry-126/frames/00.png", 19, 18, true, 22, 9, 48, 32, "exact-canonical", "inherit", 128, "item-amulet-and-superchisel-entry-126", "thatkidbobo"),
		new Record("sprite/items/13/0", "items/knife-entry-013/frames/00.png", 36, 22, true, 6, 5, 48, 32, "exact-canonical", "inherit", 128, "item-knife-entry-013", "thatkidbobo"),
		new Record("sprite/items/131/0", "items/karamja-rum-entry-131/frames/00.png", 16, 31, true, 11, 1, 48, 32, "exact-canonical", "inherit", 128, "item-karamja-rum-entry-131", "thatkidbobo"),
		new Record("sprite/items/134/0", "items/silver-entry-134/frames/00.png", 23, 12, true, 7, 13, 48, 32, "exact-canonical", "inherit", 128, "item-silver-entry-134", "thatkidbobo"),
		new Record("sprite/items/14/0", "items/logs-entry-014/frames/00.png", 44, 30, true, 3, 1, 48, 32, "exact-canonical", "inherit", 128, "item-logs-entry-014", "thatkidbobo"),
		new Record("sprite/items/143/0", "items/anti-dragon-shield-entry-143/frames/00.png", 36, 19, true, 6, 8, 48, 32, "exact-canonical", "inherit", 128, "item-anti-dragon-shield-entry-143", "thatkidbobo"),
		new Record("sprite/items/147/0", "items/pestle-and-mortar-entry-147/frames/00.png", 36, 20, true, 6, 11, 48, 32, "exact-canonical", "inherit", 128, "item-pestle-and-mortar-entry-147", "thatkidbobo"),
		new Record("sprite/items/151/0", "items/tomato-entry-151/frames/00.png", 15, 16, true, 17, 7, 48, 32, "exact-canonical", "inherit", 128, "item-tomato-entry-151", "thatkidbobo"),
		new Record("sprite/items/164/0", "items/small-fish-entry-164/frames/00.png", 35, 26, true, 6, 3, 48, 32, "exact-canonical", "inherit", 128, "item-small-fish-entry-164", "thatkidbobo"),
		new Record("sprite/items/165/0", "items/salmon-trout-and-cod-entry-165/frames/00.png", 44, 24, true, 1, 2, 48, 32, "exact-canonical", "inherit", 128, "item-salmon-trout-and-cod-entry-165", "thatkidbobo"),
		new Record("sprite/items/166/0", "items/herring-mackerel-and-pike-entry-166/frames/00.png", 44, 17, true, 1, 7, 48, 32, "exact-canonical", "inherit", 128, "item-herring-mackerel-and-pike-entry-166", "thatkidbobo"),
		new Record("sprite/items/167/0", "items/tuna-and-bass-entry-167/frames/00.png", 47, 26, true, 1, 2, 48, 32, "exact-canonical", "inherit", 128, "item-tuna-and-bass-entry-167", "thatkidbobo"),
		new Record("sprite/items/168/0", "items/swordfish-entry-168/frames/00.png", 48, 27, true, 0, 2, 48, 32, "exact-canonical", "inherit", 128, "item-swordfish-entry-168", "thatkidbobo"),
		new Record("sprite/items/169/0", "items/lobster-entry-169/frames/00.png", 40, 32, true, 2, 0, 48, 32, "exact-canonical", "inherit", 128, "item-lobster-entry-169", "thatkidbobo"),
		new Record("sprite/items/177/0", "items/cake-tin-entry-177/frames/00.png", 39, 26, true, 5, 5, 48, 32, "exact-canonical", "inherit", 128, "item-cake-tin-entry-177", "thatkidbobo"),
		new Record("sprite/items/178/0", "items/uncooked-cake-entry-178/frames/00.png", 39, 26, true, 5, 5, 48, 32, "exact-canonical", "inherit", 128, "item-uncooked-cake-entry-178", "thatkidbobo"),
		new Record("sprite/items/183/0", "items/ball-entry-183/frames/00.png", 29, 29, true, 10, 1, 48, 32, "exact-canonical", "inherit", 128, "item-ball-entry-183", "thatkidbobo"),
		new Record("sprite/items/184/0", "items/magnet-entry-184/frames/00.png", 25, 30, true, 8, 1, 48, 32, "exact-canonical", "inherit", 128, "item-magnet-entry-184", "thatkidbobo"),
		new Record("sprite/items/185/0", "items/shark-entry-185/frames/00.png", 44, 32, true, 3, 0, 48, 32, "exact-canonical", "inherit", 128, "item-shark-entry-185", "thatkidbobo"),
		new Record("sprite/items/187/0", "items/casket-and-pouches-entry-187/frames/00.png", 38, 27, true, 5, 2, 48, 32, "exact-canonical", "inherit", 128, "item-casket-and-pouches-entry-187", "thatkidbobo"),
		new Record("sprite/items/19/0", "items/egg-entry-019/frames/00.png", 13, 20, true, 16, 7, 48, 32, "exact-canonical", "inherit", 128, "item-egg-entry-019", "thatkidbobo"),
		new Record("sprite/items/193/0", "items/master-thief-armband-entry-193/frames/00.png", 27, 17, true, 12, 11, 48, 32, "exact-canonical", "inherit", 128, "item-master-thief-armband-entry-193", "thatkidbobo"),
		new Record("sprite/items/194/0", "items/lava-eel-entry-194/frames/00.png", 44, 17, true, 1, 8, 48, 32, "exact-canonical", "inherit", 128, "item-lava-eel-entry-194", "thatkidbobo"),
		new Record("sprite/items/2/0", "items/paladin-shield-entry-002/frames/00.png", 41, 26, true, 3, 3, 48, 32, "exact-canonical", "inherit", 128, "item-paladin-shield-entry-002", "thatkidbobo"),
		new Record("sprite/items/200/0", "items/blood-rune-entry-200/frames/00.png", 28, 25, true, 5, 6, 48, 32, "exact-canonical", "inherit", 128, "item-blood-rune-entry-200", "thatkidbobo"),
		new Record("sprite/items/204/0", "items/molten-glass-entry-204/frames/00.png", 40, 19, true, 4, 12, 48, 32, "exact-canonical", "inherit", 128, "item-molten-glass-entry-204", "thatkidbobo"),
		new Record("sprite/items/207/0", "items/arrowheads-entry-207/frames/00.png", 31, 21, true, 9, 5, 48, 32, "exact-canonical", "inherit", 128, "item-arrowheads-entry-207", "thatkidbobo"),
		new Record("sprite/items/210/0", "items/easter-egg-entry-210/frames/00.png", 21, 32, true, 8, 0, 48, 32, "exact-canonical", "inherit", 128, "item-easter-egg-entry-210", "thatkidbobo"),
		new Record("sprite/items/229/0", "items/holy-grail-entry-229/frames/00.png", 23, 30, true, 16, 2, 48, 32, "exact-canonical", "inherit", 128, "item-holy-grail-entry-229", "thatkidbobo"),
		new Record("sprite/items/233/0", "items/picture-entry-233/frames/00.png", 23, 31, true, 11, 1, 48, 32, "exact-canonical", "inherit", 128, "item-picture-entry-233", "thatkidbobo"),
		new Record("sprite/items/237/0", "items/corpse-remains-entry-237/frames/00.png", 39, 25, true, 4, 4, 48, 32, "exact-canonical", "inherit", 128, "item-corpse-remains-entry-237", "thatkidbobo"),
		new Record("sprite/items/26/0", "items/skull-entry-026/frames/00.png", 28, 31, true, 9, 1, 48, 32, "exact-canonical", "inherit", 128, "item-skull-entry-026", "thatkidbobo"),
		new Record("sprite/items/27/0", "items/grain-entry-027/frames/00.png", 36, 24, true, 10, 8, 48, 32, "exact-canonical", "inherit", 128, "item-grain-entry-027", "thatkidbobo"),
		new Record("sprite/items/271/0", "items/dragon-medium-helmet-entry-271/frames/00.png", 30, 26, true, 8, 5, 48, 32, "exact-canonical", "inherit", 128, "item-dragon-medium-helmet-entry-271", "thatkidbobo"),
		new Record("sprite/items/272/0", "items/dragon-battle-axe-entry-272/frames/00.png", 41, 30, true, 5, 1, 48, 32, "exact-canonical", "inherit", 128, "item-dragon-battle-axe-entry-272", "thatkidbobo"),
		new Record("sprite/items/273/0", "items/dragon-sword-entry-273/frames/00.png", 46, 26, true, 2, 6, 48, 32, "exact-canonical", "inherit", 128, "item-dragon-sword-entry-273", "thatkidbobo"),
		new Record("sprite/items/290/0", "items/lemon-entry-290/frames/00.png", 26, 23, true, 5, 3, 48, 32, "exact-canonical", "inherit", 128, "item-lemon-entry-290", "thatkidbobo"),
		new Record("sprite/items/294/0", "items/lime-entry-294/frames/00.png", 23, 23, true, 7, 2, 48, 32, "exact-canonical", "inherit", 128, "item-lime-entry-294", "thatkidbobo"),
		new Record("sprite/items/3/0", "items/square-shield-entry-003/frames/00.png", 48, 22, true, 0, 5, 48, 32, "exact-canonical", "inherit", 128, "item-square-shield-entry-003", "thatkidbobo"),
		new Record("sprite/items/328/0", "items/arrow-entry-328/frames/00.png", 33, 26, true, 7, 1, 48, 32, "exact-canonical", "inherit", 128, "item-arrow-entry-328", "thatkidbobo"),
		new Record("sprite/items/329/0", "items/lit-arrow-entry-329/frames/00.png", 35, 26, true, 4, 0, 48, 32, "exact-canonical", "inherit", 128, "item-lit-arrow-entry-329", "thatkidbobo"),
		new Record("sprite/items/365/0", "items/ogre-relic-part-entry-365/frames/00.png", 37, 29, true, 5, 2, 48, 32, "exact-canonical", "inherit", 128, "item-ogre-relic-part-entry-365", "thatkidbobo"),
		new Record("sprite/items/385/0", "items/poisoned-throwing-knife-entry-385/frames/00.png", 27, 16, true, 10, 8, 48, 32, "exact-canonical", "inherit", 128, "item-poisoned-throwing-knife-entry-385", "thatkidbobo"),
		new Record("sprite/items/4/0", "items/wooden-shield-entry-004/frames/00.png", 40, 23, true, 4, 4, 48, 32, "exact-canonical", "inherit", 128, "item-wooden-shield-entry-004", "thatkidbobo"),
		new Record("sprite/items/43/0", "items/unstrung-saradomin-symbol-entry-043/frames/00.png", 26, 26, true, 14, 3, 48, 32, "exact-canonical", "inherit", 128, "item-unstrung-saradomin-symbol-entry-043", "thatkidbobo"),
		new Record("sprite/items/434/0", "items/scythe-entry-434/frames/00.png", 36, 31, true, 8, 1, 48, 32, "exact-canonical", "inherit", 128, "item-scythe-entry-434", "thatkidbobo"),
		new Record("sprite/items/44/0", "items/saradomin-symbol-entry-044/frames/00.png", 34, 31, true, 9, 1, 48, 32, "exact-canonical", "inherit", 128, "item-saradomin-symbol-entry-044", "thatkidbobo"),
		new Record("sprite/items/5/0", "items/coif-entry-005/frames/00.png", 21, 22, true, 14, 6, 48, 32, "exact-canonical", "inherit", 128, "item-coif-entry-005", "thatkidbobo"),
		new Record("sprite/items/51/0", "items/fish-food-entry-051/frames/00.png", 23, 27, true, 16, 3, 48, 32, "exact-canonical", "inherit", 128, "item-fish-food-entry-051", "thatkidbobo"),
		new Record("sprite/items/52/0", "items/poison-entry-052/frames/00.png", 16, 31, true, 17, 1, 48, 32, "exact-canonical", "inherit", 128, "item-poison-entry-052", "thatkidbobo"),
		new Record("sprite/items/53/0", "items/spinach-roll-entry-053/frames/00.png", 30, 22, true, 8, 10, 48, 32, "exact-canonical", "inherit", 128, "item-spinach-roll-entry-053", "thatkidbobo"),
		new Record("sprite/items/60/0", "items/meat-entry-060/frames/00.png", 34, 22, true, 6, 5, 48, 32, "exact-canonical", "inherit", 128, "item-meat-entry-060", "thatkidbobo"),
		new Record("sprite/items/61/0", "items/pot-entry-061/frames/00.png", 25, 29, true, 11, 2, 48, 32, "exact-canonical", "inherit", 128, "item-pot-entry-061", "thatkidbobo"),
		new Record("sprite/items/62/0", "items/flour-and-spice-entry-062/frames/00.png", 25, 29, true, 11, 2, 48, 32, "exact-canonical", "inherit", 128, "item-flour-and-spice-entry-062", "thatkidbobo"),
		new Record("sprite/items/63/0", "items/dough-entry-063/frames/00.png", 32, 19, true, 8, 7, 48, 32, "exact-canonical", "inherit", 128, "item-dough-entry-063", "thatkidbobo"),
		new Record("sprite/items/65/0", "items/jug-entry-065/frames/00.png", 25, 25, true, 11, 4, 48, 32, "exact-canonical", "inherit", 128, "item-jug-entry-065", "thatkidbobo"),
		new Record("sprite/items/7/0", "items/chainmail-and-cuirass-entry-007/frames/00.png", 34, 18, true, 7, 7, 48, 32, "exact-canonical", "inherit", 128, "item-chainmail-and-cuirass-entry-007", "thatkidbobo"),
		new Record("sprite/items/72/0", "items/pickaxe-entry-072/frames/00.png", 44, 30, true, 2, 2, 48, 32, "exact-canonical", "inherit", 128, "item-pickaxe-entry-072", "thatkidbobo"),
		new Record("sprite/items/78/0", "items/hammer-and-blue-wizard-hat-entry-078/frames/00.png", 34, 26, true, 6, 2, 48, 32, "exact-canonical", "inherit", 128, "item-hammer-and-blue-wizard-hat-entry-078", "thatkidbobo"),
		new Record("sprite/items/79/0", "items/metal-bar-entry-079/frames/00.png", 39, 16, true, 4, 8, 48, 32, "exact-canonical", "inherit", 128, "item-metal-bar-entry-079", "thatkidbobo"),
		new Record("sprite/items/80/0", "items/dagger-and-throwing-knife-entry-080/frames/00.png", 27, 16, true, 10, 8, 48, 32, "exact-canonical", "inherit", 128, "item-dagger-and-throwing-knife-entry-080", "thatkidbobo"),
		new Record("sprite/items/81/0", "items/long-sword-entry-081/frames/00.png", 46, 25, true, 2, 2, 48, 32, "exact-canonical", "inherit", 128, "item-long-sword-entry-081", "thatkidbobo"),
		new Record("sprite/items/82/0", "items/two-handed-sword-entry-082/frames/00.png", 45, 25, true, 1, 5, 48, 32, "exact-canonical", "inherit", 128, "item-two-handed-sword-entry-082", "thatkidbobo"),
		new Record("sprite/items/83/0", "items/scimitar-entry-083/frames/00.png", 40, 29, true, 3, 2, 48, 32, "exact-canonical", "inherit", 128, "item-scimitar-entry-083", "thatkidbobo"),
		new Record("sprite/items/84/0", "items/battle-axe-entry-084/frames/00.png", 39, 30, true, 5, 1, 48, 32, "exact-canonical", "inherit", 128, "item-battle-axe-entry-084", "thatkidbobo"),
		new Record("sprite/items/85/0", "items/staff-and-hatchet-entry-085/frames/00.png", 36, 28, true, 8, 4, 48, 32, "exact-canonical", "inherit", 128, "item-staff-and-hatchet-entry-085", "thatkidbobo"),
		new Record("sprite/items/94/0", "items/oil-can-entry-094/frames/00.png", 43, 20, true, 2, 12, 48, 32, "exact-canonical", "inherit", 128, "item-oil-can-entry-094", "thatkidbobo"),
		new Record("sprite/items/97/0", "items/rubber-tube-entry-097/frames/00.png", 35, 29, true, 7, 3, 48, 32, "exact-canonical", "inherit", 128, "item-rubber-tube-entry-097", "thatkidbobo"),
		new Record("sprite/items/98/0", "items/stake-entry-098/frames/00.png", 36, 26, true, 9, 3, 48, 32, "exact-canonical", "inherit", 128, "item-stake-entry-098", "thatkidbobo"),
		new Record("sprite/npc/demon/0", "npcs/demon/frames/00.png", 50, 97, true, 24, 0, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/1", "npcs/demon/frames/01.png", 55, 95, true, 22, 2, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/10", "npcs/demon/frames/10.png", 59, 90, true, 17, 4, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/11", "npcs/demon/frames/11.png", 78, 90, true, 10, 5, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/12", "npcs/demon/frames/12.png", 50, 95, true, 28, 4, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/13", "npcs/demon/frames/13.png", 48, 96, true, 31, 3, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/14", "npcs/demon/frames/14.png", 49, 96, true, 27, 5, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/15", "npcs/demon/frames/15.png", 83, 97, true, 0, 2, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/16", "npcs/demon/frames/16.png", 101, 84, true, 4, 14, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/17", "npcs/demon/frames/17.png", 81, 96, true, 19, 0, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/2", "npcs/demon/frames/02.png", 49, 98, true, 26, 1, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/3", "npcs/demon/frames/03.png", 82, 97, true, 17, 2, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/4", "npcs/demon/frames/04.png", 42, 93, true, 28, 3, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/5", "npcs/demon/frames/05.png", 35, 97, true, 32, 2, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/6", "npcs/demon/frames/06.png", 93, 95, true, 5, 3, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/7", "npcs/demon/frames/07.png", 78, 95, true, 0, 4, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/8", "npcs/demon/frames/08.png", 100, 99, true, 0, 0, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/npc/demon/9", "npcs/demon/frames/09.png", 40, 94, true, 30, 6, 106, 101, "exact-canonical", "inherit", 128, "npc-demon", "thatkidbobo"),
		new Record("sprite/player/body1/0", "players/body1/frames/00.png", 39, 38, true, 13, 25, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/1", "players/body1/frames/01.png", 40, 37, true, 12, 25, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/10", "players/body1/frames/10.png", 38, 38, true, 15, 23, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/11", "players/body1/frames/11.png", 39, 36, true, 15, 23, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/12", "players/body1/frames/12.png", 39, 39, true, 12, 24, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/13", "players/body1/frames/13.png", 40, 38, true, 12, 24, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/14", "players/body1/frames/14.png", 39, 39, true, 13, 24, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/15", "players/body1/frames/15.png", 21, 37, true, 7, 23, 84, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/16", "players/body1/frames/16.png", 29, 37, true, 11, 23, 84, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/17", "players/body1/frames/17.png", 34, 37, true, 15, 23, 84, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/2", "players/body1/frames/02.png", 39, 38, true, 12, 25, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/3", "players/body1/frames/03.png", 40, 39, true, 14, 25, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/4", "players/body1/frames/04.png", 36, 39, true, 14, 25, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/5", "players/body1/frames/05.png", 34, 38, true, 14, 25, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/6", "players/body1/frames/06.png", 21, 39, true, 22, 23, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/7", "players/body1/frames/07.png", 18, 40, true, 22, 23, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/8", "players/body1/frames/08.png", 21, 38, true, 22, 23, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/body1/9", "players/body1/frames/09.png", 35, 39, true, 15, 23, 64, 102, "exact-canonical", "inherit", 128, "player-body1", "thatkidbobo"),
		new Record("sprite/player/fbody1/0", "players/fbody1/frames/00.png", 39, 38, true, 13, 25, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/1", "players/fbody1/frames/01.png", 38, 37, true, 13, 25, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/10", "players/fbody1/frames/10.png", 36, 38, true, 17, 23, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/11", "players/fbody1/frames/11.png", 38, 36, true, 16, 23, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/12", "players/fbody1/frames/12.png", 39, 39, true, 12, 24, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/13", "players/fbody1/frames/13.png", 40, 38, true, 12, 24, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/14", "players/fbody1/frames/14.png", 39, 39, true, 13, 24, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/15", "players/fbody1/frames/15.png", 21, 37, true, 7, 23, 84, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/16", "players/fbody1/frames/16.png", 28, 37, true, 12, 23, 84, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/17", "players/fbody1/frames/17.png", 33, 37, true, 16, 23, 84, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/2", "players/fbody1/frames/02.png", 39, 38, true, 12, 25, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/3", "players/fbody1/frames/03.png", 39, 39, true, 15, 25, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/4", "players/fbody1/frames/04.png", 35, 39, true, 15, 25, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/5", "players/fbody1/frames/05.png", 32, 38, true, 16, 25, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/6", "players/fbody1/frames/06.png", 21, 39, true, 22, 23, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/7", "players/fbody1/frames/07.png", 18, 40, true, 22, 23, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/8", "players/fbody1/frames/08.png", 21, 38, true, 22, 23, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/fbody1/9", "players/fbody1/frames/09.png", 33, 39, true, 17, 23, 64, 102, "exact-canonical", "inherit", 128, "player-fbody1", "thatkidbobo"),
		new Record("sprite/player/legs1/0", "players/legs1/frames/00.png", 26, 43, true, 17, 58, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/1", "players/legs1/frames/01.png", 26, 42, true, 19, 58, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/10", "players/legs1/frames/10.png", 23, 44, true, 20, 56, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/11", "players/legs1/frames/11.png", 22, 45, true, 20, 56, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/12", "players/legs1/frames/12.png", 26, 43, true, 19, 58, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/13", "players/legs1/frames/13.png", 26, 42, true, 19, 58, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/14", "players/legs1/frames/14.png", 25, 43, true, 20, 58, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/15", "players/legs1/frames/15.png", 34, 43, true, 0, 57, 84, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/16", "players/legs1/frames/16.png", 31, 44, true, 3, 56, 84, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/17", "players/legs1/frames/17.png", 27, 45, true, 7, 55, 84, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/2", "players/legs1/frames/02.png", 26, 43, true, 21, 58, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/3", "players/legs1/frames/03.png", 21, 44, true, 22, 56, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/4", "players/legs1/frames/04.png", 23, 44, true, 22, 56, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/5", "players/legs1/frames/05.png", 29, 44, true, 20, 56, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/6", "players/legs1/frames/06.png", 30, 42, true, 15, 58, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/7", "players/legs1/frames/07.png", 17, 42, true, 24, 58, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/8", "players/legs1/frames/08.png", 25, 42, true, 19, 58, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
		new Record("sprite/player/legs1/9", "players/legs1/frames/09.png", 27, 44, true, 18, 56, 64, 102, "exact-canonical", "inherit", 128, "player-legs1", "thatkidbobo"),
	};

	private RemasteredSpriteCatalogData() {
	}

	static final class Record {
		final String key;
		final String png;
		final int pixelWidth;
		final int pixelHeight;
		final boolean requiresShift;
		final int shiftX;
		final int shiftY;
		final int boundWidth;
		final int boundHeight;
		final String sizePolicy;
		final String recolorPolicy;
		final int alphaThreshold;
		final String setId;
		final String contributorId;

		Record(String key, String png, int pixelWidth, int pixelHeight, boolean requiresShift,
				int shiftX, int shiftY, int boundWidth, int boundHeight, String sizePolicy,
				String recolorPolicy, int alphaThreshold, String setId, String contributorId) {
			this.key = key;
			this.png = png;
			this.pixelWidth = pixelWidth;
			this.pixelHeight = pixelHeight;
			this.requiresShift = requiresShift;
			this.shiftX = shiftX;
			this.shiftY = shiftY;
			this.boundWidth = boundWidth;
			this.boundHeight = boundHeight;
			this.sizePolicy = sizePolicy;
			this.recolorPolicy = recolorPolicy;
			this.alphaThreshold = alphaThreshold;
			this.setId = setId;
			this.contributorId = contributorId;
		}
	}
}
