#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
GUIDE = ROOT / "Client_Base" / "src" / "com" / "openrsc" / "interfaces" / "misc" / "SkillGuideInterface.java"
CLIENT = ROOT / "Client_Base" / "src" / "orsc" / "mudclient.java"
CLIENT_ITEMS = ROOT / "Client_Base" / "src" / "com" / "openrsc" / "client" / "entityhandling" / "EntityHandler.java"


def fail(message: str) -> None:
    raise SystemExit(f"FAIL: {message}")


def require(text: str, needle: str, description: str) -> None:
    if needle not in text:
        fail(f"missing {description}: {needle}")


def forbid(text: str, needle: str, description: str) -> None:
    if needle in text:
        fail(f"retired {description} is still present: {needle}")


def main() -> None:
    guide = GUIDE.read_text()
    client = CLIENT.read_text()
    client_items = CLIENT_ITEMS.read_text()

    require(guide, 'populateRangedGuide();', "ranged guide helper")
    require(guide, 'addRangedBowGuide("Blood", 70, 2130, 2129);', "blood bow ranged requirement")
    require(guide, 'addRangedCrossbowGuide("Blood", 70, 2176, "Rune bolts");', "blood crossbow bolt tier")
    require(guide, 'addThrownGuide("Orichalcum", 62, 2046, 2029, 2210);', "orichalcum thrown tier")

    require(client, 'skillGuideChosenTabs.add("Daggers");', "melee daggers tab")
    require(client, 'skillGuideChosenTabs.add("Swords");', "melee swords tab")
    require(client, 'skillGuideChosenTabs.add("Scimitars");', "melee scimitars tab")
    require(client, 'skillGuideChosenTabs.add("2-Handers");', "melee 2-handers tab")
    require(client, 'skillGuideChosenTabs.add("Battleaxes");', "melee battleaxes tab")
    require(client, 'skillGuideChosenTabs.add("Maces");', "melee maces tab")
    require(client, 'skillGuideChosenTabs.add("Spears");', "melee spears tab")
    require(guide, 'addMeleeTierGuide("Tin dagger", 1, 1995);', "tin dagger melee guide")
    require(guide, 'addMeleeTierGuide("Copper long sword", 8, 2009);', "copper sword melee guide")
    require(guide, 'addMeleeTierGuide("Titan steel long sword", 46, 2020);', "titan steel sword melee guide")
    require(guide, 'addMeleeTierGuide("Orichalcum spear", 62, 2210);', "orichalcum spear melee guide")
    require(guide, 'addMeleeTierGuide("Rune spear", 70, 1092);', "rune spear melee guide")

    require(guide, 'populatePrayerGuide();', "prayer guide helper")
    require(guide, 'addPrayerLine("Magic Power", "5 tiers of magic damage bonuses");', "saradomin prayer summary")
    require(guide, 'addPrayerLine("Smithing Favor", "5 tiers of smithing XP bonuses");', "zamorak prayer summary")
    require(guide, 'addPrayerLine("Crafting Favor", "5 tiers of crafting XP bonuses");', "guthix prayer summary")
    require(guide, 'new SkillMenuItem(1214, "70", "Saradomin Cape - requires Saradomin worship")', "saradomin gear prayer guide")
    require(guide, 'new SkillMenuItem(2237, "70", "Blood staff blessed by Zamorak - requires Prayer and Magic")', "blessed blood staff prayer guide")
    require(guide, 'new SkillMenuItem(3152, "", "Saradomin blessed staves use the same tiers")', "saradomin blessed staff prayer guide")
    require(guide, 'new SkillMenuItem(3162, "", "Guthix blessed staves use the same tiers")', "guthix blessed staff prayer guide")
    require(guide, 'new SkillMenuItem(3137, "50", "Wool hats can be blessed")', "blessed wool hat prayer guide")
    require(guide, 'new SkillMenuItem(3138, "200", "Wool robe tops can be blessed")', "blessed wool robe top prayer guide")
    require(client, 'skillGuideChosenTabs.add("Devotion");', "devotion prayer guide tab")
    require(guide, 'Bury bones or scatter ashes to make offerings', "devotion offering prayer guide")
    require(guide, 'Every 10 offerings gives +1 devotion', "devotion level prayer guide")
    require(guide, 'Blessed symbols give 1.5x devotion from offerings', "blessed symbol devotion guide")
    require(guide, '+1 Prayer XP per offering for each devotion', "devotion XP prayer guide")
    require(guide, 'Devotion is tracked separately for each god', "per-god devotion guide")
    require(guide, 'Devotion ranges from -1000 to 1000', "devotion range prayer guide")
    require(guide, "You can bless items at your god's altar", "blessing altar guide")
    require(guide, 'Symbols require 25 devotion to bless', "symbol blessing devotion guide")
    require(guide, 'Blessed items grow stronger with devotion', "blessed item scaling prayer guide")
    require(guide, 'You can bless an item once you are at 50 devotion per resource cost', "blessing resource devotion guide")
    require(guide, "Destroy opposing god's blessed items at your altar", "opposing blessed item destruction guide")
    require(guide, 'Destruction lowers devotion to the item', "opposing blessed item devotion penalty guide")
    require(guide, '1 resource: daggers, short swords, maces, wool hats', "one-resource devotion unlock guide")
    require(guide, '2 resources: longs, scims, helms, gloves, boots', "two-resource devotion unlock guide")
    require(guide, '3 resources: 2-handers, battleaxes, shields, legs', "three-resource devotion unlock guide")
    require(guide, '4 resources: bodies and robe tops', "four-resource devotion unlock guide")
    require(guide, 'Basic staves require 50; blood staves require 500', "blood staff devotion unlock guide")
    require(guide, 'mc.getSkillGuideChosen().equals("Prayer") && tab.equals("Devotion")', "devotion tab should render as info text")

    require(guide, 'populateMiningGuide();', "mining guide helper")
    require(guide, 'new SkillMenuItem(1987, "1", "Tin Pickaxe")', "tin pickaxe guide")
    require(guide, 'new SkillMenuItem(2048, "46", "Titan steel Pickaxe")', "titan steel pickaxe guide")
    require(guide, 'new SkillMenuItem(2049, "62", "Orichalcum Pickaxe")', "orichalcum pickaxe guide")
    require(guide, 'new SkillMenuItem(1299, "1", "Stone")', "stone mining guide")
    require(guide, 'new SkillMenuItem(150, "8", "Copper Ore")', "copper ore guide")
    require(guide, 'new SkillMenuItem(155, "22", "Coal")', "coal guide")
    require(guide, 'new SkillMenuItem(153, "38", "Mithril Ore")', "mithril ore guide")
    require(guide, 'new SkillMenuItem(154, "54", "Adamantite Ore")', "adamantite ore guide")
    require(guide, 'new SkillMenuItem(409, "70", "Runite Ore")', "runite ore guide")

    require(guide, 'addAmmoMouldGuide("Tin", 1, 2004, 2039, 2043, 1996);', "tin ammo crafting guide")
    require(guide, 'addAmmoMouldGuide("Rune", 70, 674, 646, 1070, 1080);', "rune ammo crafting guide")
    require(guide, 'addSmithingTier("Tin", 1, 1995, 1997, 1998, 1999, 2000, 2001, 1987, 2002, 2003, 3181, 2207, -1, 1959, 1960, 1961, 2224, 1962, 1963, 1964);', "tin paladin shield smithing guide")
    require(guide, 'addSmithingTier("Rune", 70, 396, 397, 75, 398, 81, 405, 1262, 93, 3190, 98, 1092, 2194, 112, 1993, 1994, 403, 404, 402, 401);', "rune paladin shield smithing guide")
    require(guide, 'new SkillMenuItem(1958, "62", "2 Orichalcum bars - 1 mithril, 1 adamantite, and 5 coal")', "orichalcum smelting guide")
    forbid(guide, "Orichalcum bars - mithril, adamantite, silver", "orichalcum silver smelting requirement")
    forbid(guide, "Orichalcum bars - 1 mithril, 1 adamantite, 1 gold", "orichalcum gold smelting requirement")
    require(guide, 'name + " paladin shield - 3 bars"', "paladin shield smithing guide line")
    require(guide, 'addWoodcraftGuide("Basic", 10, 1, 277, 5, 276, 8, 60, 9, 100, 1);', "basic woodcraft recipe guide")
    require(guide, 'addWoodcraftGuide("Pine", 15, 8, 2116, 12, 2115, 15, 59, 16, 2131, 8);', "pine woodcraft recipe guide")
    require(guide, 'addWoodcraftGuide("Willow", 25, 22, 661, 26, 660, 29, 2170, 30, 1769, 22);', "willow base staff woodcraft guide")
    require(guide, 'addWoodcraftGuide("Maple", 35, 38, 663, 40, 662, 43, 2172, 44, 1774, 38);', "maple base staff woodcraft guide")
    require(guide, 'addWoodcraftGuide("Yew", 40, 46, 665, 47, 664, 50, 2173, 51, 1779, 46);', "yew base staff woodcraft guide")
    require(guide, 'addWoodcraftGuide("Magic", 50, 62, 667, 61, 666, 64, 2175, 65, 1784, 62);', "magic base staff woodcraft guide")
    require(guide, 'addWoodcraftGuide("Blood", 55, 70, 2128, 67, 2127, 70, 2176, 72, 2146, 70);', "blood woodcraft recipe guide")
    require(guide, 'new SkillMenuItem(779, "", "Can be opened at level 34")', "oyster pearl info wording")
    require(guide, 'new SkillMenuItem(191, "", "Crafting Guild can be entered at level 40 with a brown apron")', "crafting guild info wording")
    require(guide, 'new SkillMenuItem(1259, "", "Mining Guild can be entered at level 60")', "mining guild info wording")
    require(guide, 'new SkillMenuItem(379, "", "Fishing Guild can be entered at level 68")', "fishing guild info wording")
    require(guide, 'new SkillMenuItem(405, "", "Woodcutting Guild can be entered at level 55 after paying 1000 coins")', "woodcutting guild info wording")
    require(guide, 'new SkillMenuItem(192, "", "Cooking Guild can be entered at level 32 with a chef\'s hat")', "cooking guild info wording")
    require(guide, 'new SkillMenuItem(185, "", "Magic Guild can be entered at level 66")', "magic guild info wording")
    require(guide, 'skillName + " cape unlocked at level 99"', "skillcape guide level-99 wording helper")
    require(guide, 'addSkillCapeGuide(1527, "Enchanting");', "enchanting cape guide wording")
    require(guide, 'addSkillCapeGuide(1384, "Crafting");', "crafting cape guide wording")
    require(guide, 'addAltarGuide(33, 1, "Air Rune", "306,593");', "air altar coordinate guide")
    require(guide, 'addAltarGuide(37, 1, "Life Rune", "283,694");', "life altar coordinate guide")
    require(guide, 'addAltarGuide(46, 30, "Cosmic Rune", "104,3556");', "cosmic altar coordinate guide")
    require(guide, 'addAltarGuide(825, 62, "Soul Rune", "988,176");', "soul altar coordinate guide")
    require(guide, 'addAltarGuide(619, 70, "Blood Rune", "247,102");', "blood altar coordinate guide")

    require(guide, 'addHerblawPotionFamilyGuide(474, 477, 480, 483, 486, 3198, "Potion of Brawn", "limpwurt root");', "brawn potion family guide")
    require(guide, 'addHerblawPotionFamilyGuide(489, 492, 495, 498, 566, 3201, "Potion of Deftness", "10 fish oil");', "deftness potion family guide")
    require(guide, 'addHerblawPotionFamilyGuide(569, 963, 1411, 1414, 1468, 3204, "Potion of Insight", "eye of newt");', "insight potion family guide")
    require(guide, 'new SkillMenuItem(1471, "22", "Stat restore - Harralander & ground unicorn horn")', "stat restore guide")
    require(guide, 'new SkillMenuItem(1474, "8", "Antidote - Marrentill & red spiders\' eggs")', "antidote guide")
    require(guide, 'new SkillMenuItem(572, "23", "Weapon poison - Harralander & ground blue dragon scale")', "weapon poison guide")
    require(guide, 'new SkillMenuItem(1477, "45", "Skiller\'s Brew - Irit leaf & snape grass")', "skiller brew guide")
    require(guide, 'new SkillMenuItem(3192, "45", "Warrior\'s Brew - Irit leaf & white berries")', "warrior brew guide")
    require(guide, 'new SkillMenuItem(221, "72", "Strong Skiller\'s Brew - Dwarf weed & 5 snape grass")', "strong skiller brew guide")
    require(guide, 'new SkillMenuItem(3195, "72", "Strong Warrior\'s Brew - Dwarf weed & 5 white berries")', "strong warrior brew guide")
    require(guide, 'Brawn boosts Melee, Hits, Mining, Smithing, Woodcutting', "brawn effect guide")
    require(guide, 'Deftness boosts Ranged, Agility, Fishing, Crafting, Pickpocketing', "deftness effect guide")
    require(guide, 'Insight boosts Magic, Enchanting, Summoning, Cooking, Prayer', "insight effect guide")
    require(guide, 'Tiered potions go v1 to v6: 5%, 8%, 11%, 14%, 17%, 20%', "tier potency guide")
    require(guide, 'Skiller\'s Brew gives non-combat XP: 20% for 30 minutes', "skiller brew effect guide")
    require(guide, 'Strong Warrior\'s Brew gives combat XP: 40% for 60 minutes', "strong warrior brew effect guide")
    require(client_items, 'new ItemDef("Potion of Brawn v1"', "client brawn item name")
    require(client_items, 'new ItemDef("Potion of Deftness v5"', "client deftness v5 item name")
    require(client_items, 'new ItemDef("Potion of Deftness v6"', "client deftness v6 item name")
    require(client_items, 'new ItemDef("Potion of Brawn v6"', "client brawn v6 item name")
    require(client_items, 'new ItemDef("Potion of Insight v6"', "client insight v6 item name")
    require(client_items, 'new ItemDef("Potion of Insight v4"', "client insight v4 item name")
    require(client_items, 'new ItemDef("Stat restore"', "client stat restore item name")
    require(client_items, 'new ItemDef("Antidote"', "client antidote item name")
    require(client_items, 'new ItemDef("Skiller\'s Brew"', "client skiller brew item name")
    require(client_items, 'new ItemDef("Warrior\'s Brew"', "client warrior brew item name")
    require(client_items, 'new ItemDef("Strong Warrior\'s Brew"', "client strong warrior brew item name")

    require(client, 'skillGuideChosenTabs.add("MyWorld");', "retired fletching guide tab replacement")
    require(client, 'skillGuideChosenTabs.add("Ammo");', "crafting ammo tab")
    require(client, 'skillGuideChosenTabs.add("Woodcraft");', "crafting woodcraft tab")
    require(client, 'skillGuideChosenTabs.add("Rods");', "fishing rod tab")
    require(client, 'skillGuideChosenTabs.add("Hatchets");', "woodcutting hatchet tab")
    require(guide, 'name.equals("Spore") || name.equals("Wood Drill") || name.equals("Battering Ram")', "wood splinter guide mapping")
    require(guide, 'return "Splinter";', "wood splinter guide label")
    require(client, 'spellName.equals("spore") || spellName.equals("wood drill")', "wood splinter tooltip mapping")
    require(client, 'return "Splinter";', "wood splinter tooltip label")
    require(guide, 'Spells using mind runes will do damage equal to chaos runes', "chaos gauntlets magic guide wording")
    require(guide, 'Thunder spells can Startle and negate the next attack', "thunder dual spell guide effect")
    require(guide, 'Acid spells can Corrode and apply poison', "acid dual spell guide effect")
    require(guide, 'Ice spells can Frostbite and reflect damage', "ice dual spell guide effect")
    require(guide, 'Wood spells can Splinter to hit another NPC', "wood dual spell guide effect")

    require(guide, 'new SkillMenuItem(349, "1", "Shrimp - Fishing Rod (T1)")', "fishing shrimp rod guide")
    require(guide, 'new SkillMenuItem(366, "38", "Tuna - Maple Fishing Rod (T6)")', "fishing tuna rod guide")
    require(guide, 'new SkillMenuItem(545, "70", "Shark - Blood Fishing Rod (T10)")', "fishing shark rod guide")
    require(guide, 'new SkillMenuItem(2686, "38", "Maple Fishing Rod - T6, +25 effective Fishing")', "maple fishing rod guide")
    require(guide, 'new SkillMenuItem(2690, "70", "Blood Fishing Rod - T10, +45 effective Fishing")', "blood fishing rod guide")
    require(guide, 'new SkillMenuItem(377, "", "Rods catch their tier and 3 tiers below")', "fishing rod catch window guide")
    require(guide, 'new SkillMenuItem(439, "", "Herb rolls use shears tier and 3 tiers below")', "harvesting herb roll tier window guide")
    require(guide, 'new SkillMenuItem(2328, "1", "Gnome Stronghold Course - Tier 1 pouch per lap")', "gnome agility pouch guide")
    require(guide, 'new SkillMenuItem(2329, "35", "Barbarian Outpost Course - Tier 2 pouch per lap")', "barbarian agility pouch guide")
    require(guide, 'new SkillMenuItem(2330, "52", "Wilderness Course - Tier 3 pouch per lap")', "wilderness agility pouch guide")
    require(guide, 'new SkillMenuItem(350, "", "Shrimp - Heals 3")', "shrimp heal guide")
    require(guide, 'new SkillMenuItem(352, "", "Anchovies - Heals 1")', "anchovies heal guide")
    require(guide, 'new SkillMenuItem(765, "", "Dwellberries - Heals 2")', "dwellberries heal guide")
    require(guide, 'new SkillMenuItem(210, "", "Kebab - Variable heal or effect")', "variable kebab guide")
    require(guide, 'new SkillMenuItem(923, "", "Ugthanki Kebab - Heals 19")', "ugthanki kebab heal guide")
    require(guide, 'new SkillMenuItem(1493, "", "White pumpkin pie - Heals 16 (8 per slice)")', "white pumpkin pie heal guide")
    require(guide, 'new SkillMenuItem(546, "64", "Shark")', "shark cooking guide")
    require(guide, 'new SkillMenuItem(1191, "70", "Manta Ray")', "manta ray cooking guide")
    require(guide, 'new SkillMenuItem(325, "32", "Plain Pizza")', "plain pizza cooking guide")
    require(guide, 'new SkillMenuItem(1490, "68", "Pumpkin pie")', "pumpkin pie cooking guide")
    require(guide, 'new SkillMenuItem(1493, "68", "White pumpkin pie")', "white pumpkin pie cooking guide")
    require(guide, 'new SkillMenuItem(1463, "67", "Seaweed Soup")', "seaweed soup cooking guide")

    forbid(guide, 'new SkillMenuItem(424, "10", "Black")', "old black melee guide level")
    forbid(guide, 'new SkillMenuItem(150, "1", "Copper Ore")', "old copper mining level")
    forbid(guide, 'new SkillMenuItem(155, "30", "Coal")', "old coal mining level")
    forbid(guide, 'new SkillMenuItem(153, "55", "Mithril Ore")', "old mithril mining level")
    forbid(guide, 'new SkillMenuItem(154, "70", "Adamantite Ore")', "old adamantite mining level")
    forbid(guide, 'new SkillMenuItem(409, "85", "Runite Ore")', "old runite mining level")
    forbid(guide, 'new SkillMenuItem(156, "1", "Bronze Pickaxe")', "old bronze pickaxe level line")
    forbid(guide, 'addWoodcraftGuide("Willow", 25, 22, 661, 26, 660, 29, 2170, 30, 1765, 22);', "willow elemental staff woodcraft guide id")
    forbid(guide, 'addWoodcraftGuide("Maple", 35, 38, 663, 40, 662, 43, 2172, 44, 1766, 38);', "maple elemental staff woodcraft guide id")
    forbid(guide, 'addWoodcraftGuide("Yew", 40, 46, 665, 47, 664, 50, 2173, 51, 1767, 46);', "yew elemental staff woodcraft guide id")
    forbid(guide, 'addWoodcraftGuide("Magic", 50, 62, 667, 61, 666, 64, 2175, 65, 1768, 62);', "magic elemental staff woodcraft guide id")
    forbid(guide, 'addWoodcraftGuide("Logs", 10, 1, 277, 5, 276, 8, 60, 9, 100, 1);', "awkward logs woodcraft label")
    forbid(guide, 'new SkillMenuItem(779, "34", "Oyster Pearls")', "old oyster pearl info layout")
    forbid(guide, 'new SkillMenuItem(191, "", "Can enter Crafting Guild at level 40")', "old crafting guild info wording")
    forbid(guide, 'new SkillMenuItem(1259, "60", "Mining Guild")', "old mining guild info layout")
    forbid(guide, 'new SkillMenuItem(379, "68", "Fishing Guild")', "old fishing guild info layout")
    forbid(guide, 'new SkillMenuItem(405, "55", "Woodcutting Guild")', "old woodcutting guild info layout")
    forbid(guide, 'new SkillMenuItem(192, "32", "Cooks\' Guild")', "old cooking guild info layout")
    forbid(guide, 'new SkillMenuItem(185, "", "Wizard\'s Guild can be entered at level 66")', "old magic guild wording")
    forbid(guide, 'All throwing knives', "old ranged thrown summary")
    forbid(guide, 'Thick skin - Increases your defense by 5%', "old prayer guide")
    forbid(guide, 'Staff of Air', "legacy staff wording")
    forbid(guide, 'Potion of Regeneration', "old regeneration potion guide")
    forbid(guide, 'Potion of Speed', "old speed potion guide")
    forbid(guide, 'Potion of Luck', "old luck potion guide")
    forbid(guide, 'Potion of Notation', "old notation potion guide")
    forbid(guide, 'Potion of Magic Resistance', "old magic resistance potion guide")
    forbid(guide, 'Potion of Melee Resistance', "old melee resistance potion guide")
    forbid(guide, 'Potion of Ranged Resistance', "old ranged resistance potion guide")
    forbid(guide, 'Enchanting potion - Marrentill & 10 fish oil', "old enchanting potion guide")
    forbid(client_items, 'new ItemDef("Potion of Zamorak"', "old client potion of zamorak item name")
    forbid(client_items, 'new ItemDef("Potion of Saradomin"', "old client potion of saradomin item name")
    forbid(client_items, 'new ItemDef("Runecraft Potion"', "old client runecraft potion item name")
    forbid(client_items, 'new ItemDef("Super Runecraft Potion"', "old client super runecraft potion item name")
    forbid(guide, 'Gold Crown', "retired crown guide")
    forbid(guide, 'Battlestaves', "retired battlestaff guide")
    forbid(guide, 'Small Fishing Net', "old fishing net guide")
    forbid(guide, 'Fishing Rod and Bait', "old fishing bait guide")
    forbid(guide, 'Fly Fishing Rod and Feathers', "old fly fishing guide")
    forbid(guide, 'Big Fishing Net', "old big net guide")
    forbid(guide, 'Harpoon', "old harpoon guide")
    forbid(guide, 'Shrimp - Heals 2', "old shrimp heal guide")
    forbid(guide, 'Anchovies - Heals 2', "old anchovies heal guide")
    forbid(guide, 'Kebab - ???', "unknown kebab guide")
    forbid(guide, 'Ugthanki Kebab - ???', "unknown ugthanki kebab guide")
    forbid(guide, 'new SkillMenuItem(1492, "", "White pumkpin pie', "wrong white pumpkin pie heal id")
    forbid(guide, 'new SkillMenuItem(1492, "80", "White pumpkin pie")', "wrong white pumpkin pie cooking id")
    forbid(guide, 'new SkillMenuItem(546, "80", "Shark")', "old shark cooking level")
    forbid(guide, 'new SkillMenuItem(1191, "91", "Manta Ray")', "old manta ray cooking level")
    forbid(guide, 'new SkillMenuItem(325, "35", "Plain Pizza")', "old plain pizza cooking level")
    forbid(guide, 'new SkillMenuItem(1527, "99", "Enchanting Cape")', "terse enchanting cape guide wording")
    forbid(guide, 'Can buy Crafting Cape at level 99', "old crafting cape guide wording")
    forbid(client, 'skillGuideChosenTabs.add("Axes");', "old woodcutting axes tab")

    print("PASS: MyWorld skill guides reflect current tiers and recipes")


if __name__ == "__main__":
    main()
