#!/usr/bin/env python3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MUDCLIENT = ROOT / "Client_Base/src/orsc/mudclient.java"
GRAPHICS_CONTROLLER = ROOT / "Client_Base/src/orsc/graphics/two/GraphicsController.java"
RENDERER_2D_FRAME = ROOT / "Client_Base/src/orsc/graphics/Renderer2DFrame.java"
RENDERER_2D_SETTINGS = ROOT / "Client_Base/src/orsc/graphics/Renderer2DSettings.java"
RSMODEL = ROOT / "Client_Base/src/orsc/graphics/three/RSModel.java"
SCENE = ROOT / "Client_Base/src/orsc/graphics/three/Scene.java"
GEOMETRY_FRAME = ROOT / "Client_Base/src/orsc/graphics/three/Renderer3DFrame.java"
DEPTH_FRAME = ROOT / "Client_Base/src/orsc/graphics/three/Renderer3DDepthFrame.java"
MESH_FRAME = ROOT / "Client_Base/src/orsc/graphics/three/Renderer3DMeshFrame.java"
TEXTURE_DATA = ROOT / "Client_Base/src/orsc/graphics/three/Renderer3DTextureData.java"
GEOMETRY_SETTINGS = ROOT / "Client_Base/src/orsc/graphics/three/Renderer3DSettings.java"
GEOMETRY_KIND = ROOT / "Client_Base/src/orsc/graphics/three/Renderer3DModelKind.java"
WORLD = ROOT / "Client_Base/src/orsc/graphics/three/World.java"
TELEMETRY = ROOT / "Client_Base/src/orsc/RenderTelemetry.java"
APPLET = ROOT / "PC_Client/src/orsc/ORSCApplet.java"
SCALED_WINDOW = ROOT / "PC_Client/src/orsc/ScaledWindow.java"
OPENGL_PRESENTER = ROOT / "PC_Client/src/orsc/OpenGLFramePresenter.java"
PLAN = ROOT / "docs/myworld/renderer-v2-plan.md"


def require(text: str, needle: str, label: str) -> None:
    if needle not in text:
        raise AssertionError(f"{label} missing expected snippet: {needle!r}")


def main() -> None:
    mudclient = MUDCLIENT.read_text(encoding="utf-8")
    graphics_controller = GRAPHICS_CONTROLLER.read_text(encoding="utf-8")
    renderer_2d_frame = RENDERER_2D_FRAME.read_text(encoding="utf-8")
    renderer_2d_settings = RENDERER_2D_SETTINGS.read_text(encoding="utf-8")
    rsmodel = RSMODEL.read_text(encoding="utf-8")
    scene = SCENE.read_text(encoding="utf-8")
    geometry_frame = GEOMETRY_FRAME.read_text(encoding="utf-8")
    depth_frame = DEPTH_FRAME.read_text(encoding="utf-8")
    mesh_frame = MESH_FRAME.read_text(encoding="utf-8")
    texture_data = TEXTURE_DATA.read_text(encoding="utf-8")
    geometry_settings = GEOMETRY_SETTINGS.read_text(encoding="utf-8")
    geometry_kind = GEOMETRY_KIND.read_text(encoding="utf-8")
    world = WORLD.read_text(encoding="utf-8")
    telemetry = TELEMETRY.read_text(encoding="utf-8")
    applet = APPLET.read_text(encoding="utf-8")
    scaled_window = SCALED_WINDOW.read_text(encoding="utf-8")
    opengl_presenter = OPENGL_PRESENTER.read_text(encoding="utf-8")
    plan = PLAN.read_text(encoding="utf-8")

    require(rsmodel, "public int hideBackFacesMatching(int texture)", "model back-face normalization helper")
    require(mudclient, 'private static final String TIN_ROCK_MODEL_NAME = "tinrock1";', "tin rock model marker")
    require(mudclient, "private static final int TIN_ROCK_LEGACY_RED_BACK_FACE = -15361;", "tin rock legacy red back-face marker")
    require(mudclient, "model.hideBackFacesMatching(TIN_ROCK_LEGACY_RED_BACK_FACE);", "tin rock load-boundary fix")

    require(geometry_settings, 'GEOMETRY_CAPTURE_ENV = "SPOILED_MILK_RENDERER3D_GEOMETRY_CAPTURE"', "3D geometry capture flag")
    require(geometry_settings, 'VISIBLE_WORLD_ENV = "SPOILED_MILK_RENDERER3D_VISIBLE_WORLD"', "visible world flag")
    require(geometry_settings, "VISIBLE_WORLD_ENABLED || readBoolean(GEOMETRY_CAPTURE_PROPERTY, GEOMETRY_CAPTURE_ENV)", "visible world implies geometry capture")
    require(geometry_kind, "TERRAIN(\"terrain\")", "terrain geometry kind")
    require(geometry_kind, "WALL(\"wall\")", "wall geometry kind")
    require(geometry_kind, "ROOF(\"roof\")", "roof geometry kind")
    require(geometry_kind, "GAME_OBJECT(\"object\")", "game object geometry kind")
    require(geometry_kind, "WALL_OBJECT(\"wallObject\")", "wall object geometry kind")
    require(rsmodel, "private Renderer3DModelKind renderer3DModelKind = Renderer3DModelKind.UNCLASSIFIED;", "model kind storage")
    require(rsmodel, "public void setRenderer3DModelKind(Renderer3DModelKind renderer3DModelKind)", "model kind setter")
    require(rsmodel, "var3.renderer3DModelKind = this.renderer3DModelKind;", "clone model kind propagation")
    require(rsmodel, "output[i].renderer3DModelKind = this.renderer3DModelKind;", "grid split model kind propagation")
    require(world, "tagRenderer3DModels(this.modelLandscapeGrid, Renderer3DModelKind.TERRAIN);", "terrain model tagging")
    require(world, "tagRenderer3DModels(this.modelWallGrid[plane], Renderer3DModelKind.WALL);", "wall model tagging")
    require(world, "tagRenderer3DModels(this.modelRoofGrid[plane], Renderer3DModelKind.ROOF);", "roof model tagging")
    require(mudclient, "model.setRenderer3DModelKind(Renderer3DModelKind.WALL_OBJECT);", "wall object model tagging")
    require(mudclient, "this.gameObjectInstanceModel[i].setRenderer3DModelKind(Renderer3DModelKind.GAME_OBJECT);", "game object setter tagging")
    require(renderer_2d_frame, "private final int legacySpriteId;", "2D sprite command legacy sprite id storage")
    require(renderer_2d_frame, "public int getLegacySpriteId()", "2D sprite command legacy sprite id accessor")
    require(renderer_2d_settings, "OPENGL_WORLD_SPRITES_VISIBLE_ENABLED", "2D command capture world sprite flag")
    require(renderer_2d_settings, "public static boolean isOpenGLSpriteCaptureEnabled()", "2D sprite capture setting")
    require(renderer_2d_settings, "|| OPENGL_WORLD_SPRITES_VISIBLE_ENABLED\n\t\t\t|| OPENGL_WORLD_UI_REPLAY_ENABLED;", "2D sprite capture enables world sprite and UI replay diagnostics")
    require(graphics_controller, "private int renderer2DLegacySpriteId = -1;", "2D renderer scoped legacy sprite id")
    require(graphics_controller, "Renderer2DSettings.isOpenGLSpriteCaptureEnabled()", "2D command stream capture gate")
    require(graphics_controller, "renderer2DLegacySpriteId = index;", "drawEntity legacy sprite id scope")
    require(graphics_controller, "renderer2DLegacySpriteId = previousLegacySpriteId;", "drawEntity legacy sprite id restore")
    require(graphics_controller, "mirrorX || destColumnSkewPerRow != 0,\n\t\t\t\trenderer2DLegacySpriteId,", "masked scaled sprite legacy sprite id capture")
    require(scene, "private Renderer3DFrame renderer3DFrame;", "scene geometry frame storage")
    require(scene, "Renderer3DSettings.isGeometryCaptureEnabled()", "scene geometry capture opt-in")
    require(scene, "private Renderer3DTextureData[] renderer3DTextures", "scene renderer-v2 texture catalog storage")
    require(scene, "this.renderer3DTextures = new Renderer3DTextureData[var4];", "scene renderer-v2 texture catalog allocation")
    require(scene, "Renderer3DTextureData.fromLegacyPalette(var1, var3, var4, var5)", "scene renderer-v2 texture catalog load")
    require(scene, "geometryFrame.addWorldFace(", "visible world face capture")
    require(scene, "int legacySceneDrawOrder = 0;", "legacy sorted scene draw-order counter")
    require(scene, "geometryFrame.addSpriteAnchor(", "legacy sorted sprite anchor capture")
    require(scene, "geometryFrame.recordLegacyDrawOrder(var25.modelIndex, var3, legacySceneDrawOrder);", "legacy sorted world draw-order capture")
    require(scene, "private final int[] renderer3DClippedCameraX = new int[40];", "renderer-v2 clipped camera x scratch")
    require(scene, "geometryFrame.recordLegacyClippedGeometry(", "legacy clipped world geometry capture")
    require(scene, "this.m_r,\n\t\t\t\t\t\t\t\tvar14", "legacy light/fog capture")
    require(scene, "Renderer3DDepthFrame.render(", "diagnostic depth-buffer pass")
    require(scene, "geometryFrame.setMeshFrame(Renderer3DMeshFrame.build(geometryFrame, staticWorldKinds));", "GPU-ready mesh frame build")
    require(scene, "Renderer3DModelKind.TERRAIN,", "terrain depth filter")
    require(scene, "Renderer3DModelKind.WALL,", "wall depth filter")
    require(scene, "Renderer3DModelKind.GAME_OBJECT,", "game object depth filter")
    require(scene, "Renderer3DModelKind.WALL_OBJECT", "wall object depth filter")
    require(scene, "geometryFrame.getDepthFrame().copyColorTo(this.pixelData);", "visible depth-world framebuffer copy")
    require(scene, "public Renderer3DFrame getRenderer3DFrame()", "geometry frame accessor")

    require(geometry_frame, "public final class Renderer3DFrame", "geometry frame class")
    require(geometry_frame, "public static final class FaceCommand", "geometry face command")
    require(geometry_frame, "private final int[] worldFaceCountsByKind = new int[Renderer3DModelKind.values().length];", "per-kind face counters")
    require(geometry_frame, "private final Map<Long, FaceCommand> worldFacesByModelFace = new HashMap<Long, FaceCommand>();", "world face lookup for sorted order")
    require(geometry_frame, "private final List<SpriteAnchor> spriteAnchors = new ArrayList<SpriteAnchor>();", "sprite anchor storage")
    require(geometry_frame, "private Renderer3DDepthFrame depthFrame;", "depth frame storage")
    require(geometry_frame, "private Renderer3DMeshFrame meshFrame;", "mesh frame storage")
    require(geometry_frame, "private final Renderer3DTextureData[] textures;", "geometry frame texture catalog storage")
    require(geometry_frame, "public Renderer3DTextureData[] getTextures()", "geometry frame texture catalog accessor")
    require(geometry_frame, "public Renderer3DTextureData getTexture(int textureId)", "geometry frame texture lookup")
    require(geometry_frame, "public int getColor()", "face color accessor")
    require(geometry_frame, "Renderer3DModelKind modelKind = model.getRenderer3DModelKind();", "face kind capture")
    require(geometry_frame, "cameraZ[vertex] = model.vertZRot[modelVertex];", "camera-space depth capture")
    require(geometry_frame, "screenX[vertex] = model.vertexParam6[modelVertex];", "projected x capture")
    require(geometry_frame, "screenY[vertex] = model.vertexParam2[modelVertex];", "projected y capture")
    require(geometry_frame, "private final float[] textureU;", "face texture u storage")
    require(geometry_frame, "private final float[] textureV;", "face texture v storage")
    require(geometry_frame, "private int legacyDrawOrder = -1;", "face legacy draw-order storage")
    require(geometry_frame, "void recordLegacyDrawOrder(int modelIndex, int faceId, int drawOrder)", "face legacy draw-order writer")
    require(geometry_frame, "void recordLegacyClippedGeometry(", "face clipped geometry writer")
    require(geometry_frame, "public int getLegacyDrawOrder()", "face legacy draw-order accessor")
    require(geometry_frame, "public static final class SpriteAnchor", "sprite anchor command")
    require(geometry_frame, "void addSpriteAnchor(", "sprite anchor writer")
    require(geometry_frame, "public int getSpriteAnchorCount()", "sprite anchor count accessor")
    require(geometry_frame, "public List<SpriteAnchor> getSpriteAnchors()", "sprite anchor list accessor")
    require(geometry_frame, "private final int legacyDrawOrder;", "sprite anchor legacy draw-order storage")
    require(geometry_frame, "private final int drawWidth;", "sprite anchor projected width storage")
    require(geometry_frame, "public int getPickIndex()", "sprite anchor pick index accessor")
    require(geometry_frame, "public int getAverageDepth()", "sprite anchor average depth accessor")
    require(geometry_frame, "public int getDrawX()", "sprite anchor draw x accessor")
    require(geometry_frame, "public int getHorizontalSkew()", "sprite anchor skew accessor")
    require(geometry_frame, "private int[] clippedCameraX;", "face clipped camera x storage")
    require(geometry_frame, "private int[] clippedLight;", "face clipped light storage")
    require(geometry_frame, "public int[] getRenderLight()", "face render light accessor")
    require(geometry_frame, "private float[] clippedTextureU;", "face clipped texture u storage")
    require(geometry_frame, "public int getRenderVertexCount()", "face render vertex count accessor")
    require(geometry_frame, "public int[] getRenderCameraZ()", "face render depth accessor")
    require(geometry_frame, "public int[] getRenderScreenX()", "face render screen x accessor")
    require(geometry_frame, "public float[] getRenderTextureU()", "face render texture u accessor")
    require(geometry_frame, "private void setLegacyClippedGeometry(", "face clipped geometry storage")
    require(geometry_frame, "private static long worldFaceKey(int modelIndex, int faceId)", "face lookup key helper")
    require(geometry_frame, "private void populateTextureCoordinates(", "face texture coordinate derivation")
    require(geometry_frame, "double determinant = uu * vv - uv * uv;", "face texture basis solve")
    require(geometry_frame, "public float[] getTextureU()", "face texture u accessor")
    require(geometry_frame, "public float[] getTextureV()", "face texture v accessor")
    require(depth_frame, "public final class Renderer3DDepthFrame", "depth frame class")
    require(depth_frame, "private final int[] color;", "visible depth color buffer")
    require(depth_frame, "static Renderer3DDepthFrame render(Renderer3DFrame frame, EnumSet<Renderer3DModelKind> includedKinds)", "depth render entry point")
    require(depth_frame, "public void copyColorTo(int[] destination)", "visible depth copy")
    require(depth_frame, "depth[pixel] = z;", "depth write")
    require(depth_frame, "color[pixel] = shadeColor(face.getColor(), z, face.getModelKind());", "depth-tested color write")
    require(depth_frame, "pixelWriteCount++;", "depth pixel write counter")
    require(mesh_frame, "public final class Renderer3DMeshFrame", "mesh frame class")
    require(mesh_frame, "public static final int FLOATS_PER_VERTEX = 14;", "mesh vertex layout")
    require(mesh_frame, "public static final int SCREEN_X_OFFSET = 3;", "mesh projected x offset")
    require(mesh_frame, "public static final int CAMERA_Z_OFFSET = 2;", "mesh depth offset")
    require(mesh_frame, "public static final int TEXTURE_U_OFFSET = 8;", "mesh texture u offset")
    require(mesh_frame, "public static final int TEXTURE_V_OFFSET = 9;", "mesh texture v offset")
    require(mesh_frame, "public static final int TEXTURE_RED_OFFSET = 10;", "mesh texture light red offset")
    require(mesh_frame, "static Renderer3DMeshFrame build(Renderer3DFrame frame, EnumSet<Renderer3DModelKind> includedKinds)", "mesh build entry point")
    require(mesh_frame, "private final int centerX;", "mesh projection center x storage")
    require(mesh_frame, "private final int centerY;", "mesh projection center y storage")
    require(mesh_frame, "private final int[] triangleTextures;", "mesh triangle texture material storage")
    require(mesh_frame, "private final int[] triangleFallbackColors;", "mesh triangle fallback color storage")
    require(mesh_frame, "private final Renderer3DModelKind[] triangleModelKinds;", "mesh triangle model kind storage")
    require(mesh_frame, "private final int[] triangleModelIndices;", "mesh triangle model index storage")
    require(mesh_frame, "private final int[] triangleFaceIds;", "mesh triangle face id storage")
    require(mesh_frame, "private final int[] triangleAverageDepths;", "mesh triangle average depth storage")
    require(mesh_frame, "private final int[] triangleLegacyDrawOrders;", "mesh triangle legacy draw-order storage")
    require(mesh_frame, "private final Renderer3DTextureData[] textures;", "mesh texture catalog storage")
    require(mesh_frame, "private int skippedTriangleCount;", "mesh skipped triangle counter")
    require(mesh_frame, "private int texturedTriangleCount;", "mesh textured triangle counter")
    require(mesh_frame, "private int flatColorTriangleCount;", "mesh flat color triangle counter")
    require(mesh_frame, "private int transparentTriangleCount;", "mesh transparent triangle counter")
    require(mesh_frame, "triangleCapacity += Math.max(0, face.getRenderVertexCount() - 2);", "mesh fan triangulation capacity")
    require(mesh_frame, "indices[indexCount++] = firstVertex;", "mesh index write")
    require(mesh_frame, "vertices[offset + CAMERA_X_OFFSET] = face.getRenderCameraX()[vertex];", "mesh camera coordinate write")
    require(mesh_frame, "vertices[offset + TEXTURE_U_OFFSET] = face.getRenderTextureU()[vertex];", "mesh texture u write")
    require(mesh_frame, "vertices[offset + TEXTURE_V_OFFSET] = face.getRenderTextureV()[vertex];", "mesh texture v write")
    require(mesh_frame, "vertices[offset + TEXTURE_RED_OFFSET] = textureLight;", "mesh texture light write")
    require(mesh_frame, "private float textureLightForFace(Renderer3DFrame.FaceCommand face, int vertex)", "mesh texture light helper")
    require(mesh_frame, "int[] lights = face.getRenderLight();", "mesh texture light source")
    require(mesh_frame, "color = shadedFallbackColorForFace(face, color, legacyLight);", "mesh shaded fallback material color")
    require(mesh_frame, "private int legacyFlatResourceColor(int color, int legacyLight)", "mesh legacy flat terrain shade ramp")
    require(mesh_frame, "int shadeSquared = shade * shade;", "mesh legacy flat shade squared ramp")
    require(mesh_frame, "RendererTransparency.LEGACY_TEXTURE_COLOR_MASK", "mesh legacy texture shade bands")
    require(mesh_frame, "private int fallbackColorForFace(Renderer3DFrame.FaceCommand face)", "mesh texture average fallback color helper")
    require(mesh_frame, "textureData.getAverageOpaqueRgb()", "mesh texture-backed fallback uses average opaque texture color")
    require(mesh_frame, "private void addTriangleMaterial(Renderer3DFrame.FaceCommand face)", "mesh material metadata writer")
    require(mesh_frame, "triangleTextures[triangle] = texture;", "mesh texture id write")
    require(mesh_frame, "triangleFallbackColors[triangle] = face.getColor();", "mesh fallback color write")
    require(mesh_frame, "triangleModelKinds[triangle] = face.getModelKind();", "mesh model kind material write")
    require(mesh_frame, "triangleAverageDepths[triangle] = face.getAverageDepth();", "mesh average depth material write")
    require(mesh_frame, "triangleLegacyDrawOrders[triangle] = face.getLegacyDrawOrder();", "mesh legacy draw-order write")
    require(mesh_frame, "public int getTexturedTriangleCount()", "mesh textured count accessor")
    require(mesh_frame, "public int[] getTriangleTextures()", "mesh texture array accessor")
    require(mesh_frame, "public int[] getTriangleLegacyDrawOrders()", "mesh legacy draw-order accessor")
    require(mesh_frame, "public Renderer3DTextureData[] getTextures()", "mesh texture catalog accessor")
    require(mesh_frame, "public Renderer3DTextureData getTexture(int textureId)", "mesh texture lookup")
    require(mesh_frame, "public int getAvailableTextureCount()", "mesh available texture count")
    require(texture_data, "public final class Renderer3DTextureData", "renderer-v2 texture data class")
    require(texture_data, "static Renderer3DTextureData fromLegacyPalette", "renderer-v2 legacy texture converter")
    require(texture_data, "RendererTransparency.normalizeLegacyTexturePaletteColor", "renderer-v2 texture palette normalization")
    require(texture_data, "private final int averageOpaqueRgb;", "renderer-v2 texture average opaque color storage")
    require(texture_data, "public int getAverageOpaqueRgb()", "renderer-v2 texture average opaque color accessor")
    require(texture_data, "public ByteBuffer copyToDirectRgbaBuffer()", "renderer-v2 texture upload buffer")
    require(mesh_frame, "private boolean isDrawableTriangle(Renderer3DFrame.FaceCommand face, int a, int b, int c)", "mesh drawable triangle gate")
    require(mesh_frame, "int[] cameraZ = face.getRenderCameraZ();", "mesh render depth source")
    require(mesh_frame, "cameraZ[a] <= 0", "mesh positive depth guard")
    require(mesh_frame, "maxX < 0 || minX >= viewportWidth || maxY < 0 || minY >= viewportHeight", "mesh viewport rejection guard")
    require(mesh_frame, "viewportWidth + marginX", "mesh oversized projection guard")
    require(telemetry, "int terrainFaces,", "typed world geometry telemetry recorder")
    require(telemetry, "int spriteAnchors,", "sprite anchor telemetry recorder")
    require(telemetry, "int depthTriangles,", "depth telemetry recorder")
    require(telemetry, "int meshVertices,", "mesh telemetry recorder")
    require(telemetry, "int meshTexturedTriangles,", "mesh material telemetry recorder")
    require(telemetry, "worldMeshTexturedTriangleStats.record(meshTexturedTriangles);", "mesh textured material telemetry")
    require(telemetry, '"[renderer-v2 telemetry] world mesh materials avg: textured="', "mesh material telemetry log")
    require(telemetry, "recordOpenGLWorldMeshFrame(int vertices, int indices, int triangles)", "OpenGL mesh telemetry recorder")
    require(telemetry, "openGLWorldMeshVertexStats.record(vertices);", "OpenGL mesh vertex telemetry")
    require(telemetry, "recordOpenGLWorldTextureFrame(", "OpenGL world texture telemetry recorder")
    require(telemetry, "openGLWorldTextureReferencedStats.record(referencedTextures);", "OpenGL world texture referenced telemetry")
    require(telemetry, "recordOpenGLWorldSpriteFrame(int anchors, int matched, int drawn)", "OpenGL world sprite telemetry recorder")
    require(telemetry, "openGLWorldSpriteDrawnStats.record(drawn);", "OpenGL world sprite drawn telemetry")
    require(telemetry, '"[renderer-v2 telemetry] opengl world textures avg: referenced="', "OpenGL world texture telemetry log")
    require(telemetry, '"[renderer-v2 telemetry] opengl world sprites avg: anchors="', "OpenGL world sprite telemetry log")
    require(telemetry, '"[renderer-v2 telemetry] world geometry avg: models="', "world geometry telemetry log")
    require(applet, '"world geom models " + telemetry.worldGeometryModelAverage', "world geometry overlay line")
    require(applet, '+ " anchors " + telemetry.worldSpriteAnchorAverage', "sprite anchor overlay count")
    require(applet, '"geom t/w/r/o/wo/x " + telemetry.worldGeometryTerrainFaceAverage', "typed geometry overlay line")
    require(applet, '"depth faces/tri/pix " + telemetry.worldDepthFaceAverage', "depth overlay line")
    require(applet, '"mesh v/i/t " + telemetry.worldMeshVertexAverage', "mesh overlay line")
    require(applet, '"gl mesh v/i/t " + telemetry.openGLWorldMeshVertexAverage', "OpenGL mesh overlay line")
    require(applet, '"gl sprites a/m/d " + telemetry.openGLWorldSpriteAnchorAverage', "OpenGL world sprite overlay line")
    require(applet, "Renderer3DFrame renderer3DFrame = getRenderer3DFrame();", "applet 3D frame handoff")
    require(mudclient, "public boolean isRenderer3DWorldReady()", "client renderer-v2 world readiness accessor")
    require(mudclient, "this.hasCompletedInitialRegionLoad = false;", "client clears renderer-v2 world readiness on reset")
    require(applet, "mudclient == null || !mudclient.isRenderer3DWorldReady() || mudclient.getScene() == null", "applet skips 3D mesh before region is ready")
    require(applet, "return mudclient.getScene().getRenderer3DFrame();", "applet 3D frame lookup")
    require(applet, "private void presentLoadingFrame(String state, int percent, int var3)", "OpenGL-primary loading frame presenter")
    require(applet, "scaledWindow.setGameImage(game_image);", "loading frame ScaledWindow presentation")
    require(scaled_window, "Renderer3DFrame renderer3DFrame", "scaled window 3D frame parameter")
    require(scaled_window, "openGLFramePresenter.present(\n\t\t\t\topenGLImage,", "primary OpenGL mesh handoff")
    require(opengl_presenter, 'WORLD_MESH_ENV = "SPOILED_MILK_OPENGL_WORLD_MESH"', "OpenGL world mesh flag")
    require(opengl_presenter, 'WORLD_MESH_VISIBLE_ENV = "SPOILED_MILK_OPENGL_WORLD_MESH_VISIBLE"', "OpenGL visible world mesh flag")
    require(opengl_presenter, 'WORLD_MESH_TEXTURED_VISIBLE_ENV = "SPOILED_MILK_OPENGL_WORLD_TEXTURED_VISIBLE"', "OpenGL visible textured world flag")
    require(opengl_presenter, 'WORLD_MESH_TEXTURED_STATIC_VISIBLE_ENV =\n\t\t"SPOILED_MILK_OPENGL_WORLD_TEXTURED_STATIC_VISIBLE"', "OpenGL visible textured static world flag")
    require(opengl_presenter, 'WORLD_MESH_TEXTURED_ALPHA_ENV = "SPOILED_MILK_OPENGL_WORLD_TEXTURED_ALPHA"', "OpenGL textured diagnostic alpha flag")
    require(opengl_presenter, "readFloat(WORLD_MESH_TEXTURED_ALPHA_PROPERTY, WORLD_MESH_TEXTURED_ALPHA_ENV, 1.0f, 0.0f, 1.0f)", "OpenGL textured diagnostic alpha default")
    require(opengl_presenter, 'WORLD_REPLACEMENT_COMPOSITE_ENV =\n\t\t"SPOILED_MILK_OPENGL_WORLD_REPLACEMENT_COMPOSITE"', "OpenGL world replacement composite flag")
    require(opengl_presenter, "private boolean shouldUseOpenGLWorldReplacementComposite(Frame frame)", "OpenGL world replacement composite gate")
    require(opengl_presenter, "if (!worldReplacementComposite) {\n\t\t\trunOpenGLPass(() -> drawTexturedQuad());", "OpenGL replacement skips completed software base")
    require(opengl_presenter, "command.getPhase() != Renderer2DFrame.Phase.SCENE", "OpenGL replacement restores visible scene sprites")
    require(opengl_presenter, '"visible-scene"', "OpenGL replacement visible scene sprite logging")
    require(opengl_presenter, "logCompositeSpriteCommand(\"skip-visible\"", "OpenGL replacement visible sprite debug logging")
    require(opengl_presenter, "gl.glEnable(gl.GL_ALPHA_TEST);", "OpenGL opaque textured world alpha test")
    require(opengl_presenter, "gl.glAlphaFunc(gl.GL_GREATER, 0.5f);", "OpenGL opaque textured world alpha cutoff")
    require(opengl_presenter, "terrain textures incorrectly win over later scenery/wall faces", "OpenGL textured color pass disables depth rejection")
    require(opengl_presenter, "private void drawFlatColorBatch(WorldMeshTextureBatch batch)", "OpenGL flat world batch draw")
    require(opengl_presenter, "gl.glColorPointer(", "OpenGL flat world vertex color pointer")
    require(opengl_presenter, "isFlatColorMaterial(textureId)", "OpenGL flat world material detection")
    require(opengl_presenter, "TEXTURE_LIGHT_COMPONENT_COUNT = 4", "OpenGL textured world light modulation")
    require(opengl_presenter, "private boolean canSampleTextureForKind(Renderer3DModelKind modelKind)", "OpenGL world texture sampling gate")
    require(opengl_presenter, 'WORLD_STATIC_TEXTURES_ENV =\n\t\t"SPOILED_MILK_OPENGL_WORLD_STATIC_TEXTURES"', "OpenGL static texture sampling flag")
    require(opengl_presenter, "return WORLD_STATIC_TEXTURES", "OpenGL static texture sampling opt-in")
    require(opengl_presenter, "private boolean isReasonableProjectedTriangle(", "OpenGL projected triangle guard")
    require(opengl_presenter, "buildPaddedRgbaPixels(", "OpenGL atlas border padding")
    require(opengl_presenter, "texelCenterU(placement.x)", "OpenGL atlas texel-center sampling")
    require(opengl_presenter, 'glAlphaFunc = method(gl11Class, "glAlphaFunc", int.class, float.class);', "OpenGL alpha function binding")
    require(opengl_presenter, 'WORLD_SPRITES_VISIBLE_ENV = "SPOILED_MILK_OPENGL_WORLD_SPRITES_VISIBLE"', "OpenGL visible world sprites flag")
    require(opengl_presenter, 'log("OpenGL world sprite diagnostic active.");', "OpenGL world sprite startup log")
    require(opengl_presenter, "private OpenGLWorldMeshRenderer worldMeshRenderer;", "OpenGL world mesh renderer field")
    require(opengl_presenter, "import orsc.graphics.three.Renderer3DModelKind;", "OpenGL model kind import")
    require(opengl_presenter, "import orsc.graphics.three.Renderer3DTextureData;", "OpenGL renderer-v2 texture import")
    require(opengl_presenter, "private interface OpenGLPassAction", "OpenGL pass action interface")
    require(opengl_presenter, "private void runOpenGLPass(OpenGLPassAction action)", "OpenGL pass state guard")
    require(opengl_presenter, "uploadTexture(frame);", "OpenGL base framebuffer upload")
    require(opengl_presenter, "private void prepareBaseFramebufferPass()", "OpenGL base framebuffer state reset")
    require(opengl_presenter, "runOpenGLPass(() -> drawTexturedQuad());", "OpenGL framebuffer pass guard")
    require(opengl_presenter, "runOpenGLPass(() -> drawWorldMesh(frame));", "OpenGL world pass guard")
    require(opengl_presenter, "runOpenGLPass(() -> drawWorldSprites(frame));", "OpenGL world sprite pass guard")
    require(opengl_presenter, "runOpenGLPass(() -> drawSpriteOverlay(frame));", "OpenGL sprite pass guard")
    require(opengl_presenter, "gl.glPushAttrib(gl.GL_ALL_ATTRIB_BITS);", "OpenGL server-state push")
    require(opengl_presenter, "gl.glPushClientAttrib(gl.GL_CLIENT_ALL_ATTRIB_BITS);", "OpenGL client-state push")
    require(opengl_presenter, "gl.glPopClientAttrib();", "OpenGL client-state pop")
    require(opengl_presenter, "gl.glPopAttrib();", "OpenGL server-state pop")
    require(opengl_presenter, "gl.glBufferData(gl.GL_ARRAY_BUFFER, vertexUploadBuffer, gl.GL_STREAM_DRAW);", "OpenGL vertex buffer upload")
    require(opengl_presenter, "private static final int UPLOAD_FLOATS_PER_VERTEX = 12;", "OpenGL textured vertex upload layout")
    require(opengl_presenter, "private static final int TEXTURE_COORD_COMPONENT_COUNT = 2;", "OpenGL texture coordinate component count")
    require(opengl_presenter, "private static final int TEXTURE_LIGHT_OFFSET_BYTES", "OpenGL texture light stride offset")
    require(opengl_presenter, "private static final float TEXTURED_DIAGNOSTIC_ALPHA =", "OpenGL textured diagnostic alpha")
    require(opengl_presenter, "private static float readFloat(", "OpenGL float flag parser")
    require(opengl_presenter, "private static final int TEXTURE_COORD_OFFSET_BYTES", "OpenGL texture coordinate stride offset")
    require(opengl_presenter, "private final int texturedIndexBufferId;", "OpenGL textured index buffer field")
    require(opengl_presenter, "gl.glBufferData(gl.GL_ELEMENT_ARRAY_BUFFER, indexUploadBuffer, gl.GL_STREAM_DRAW);", "OpenGL index buffer upload")
    require(opengl_presenter, "gl.glBufferData(gl.GL_ELEMENT_ARRAY_BUFFER, texturedIndexUploadBuffer, gl.GL_STREAM_DRAW);", "OpenGL textured index buffer upload")
    require(opengl_presenter, "private final OpenGLWorldTextureCache textureCache;", "OpenGL world texture cache field")
    require(opengl_presenter, "textureCache.uploadReferencedTextures(meshFrame);", "OpenGL world texture cache upload")
    require(opengl_presenter, "RenderTelemetry.recordOpenGLWorldTextureFrame(", "OpenGL world texture telemetry call")
    require(opengl_presenter, "RenderTelemetry.recordOpenGLWorldSpriteFrame(anchors.size(), matched, drawn);", "OpenGL world sprite telemetry call")
    require(opengl_presenter, "private static final class OpenGLWorldTextureCache", "OpenGL world texture cache class")
    require(opengl_presenter, "private OpenGLTextureRegion upload(Renderer3DTextureData textureData)", "OpenGL world texture atlas upload overload")
    require(opengl_presenter, "private OpenGLTextureRegion getRegion(Renderer3DMeshFrame meshFrame, int textureId)", "OpenGL world texture atlas lookup")
    require(opengl_presenter, "private int copyTexturedIndices(Renderer3DMeshFrame meshFrame, int indexCount)", "OpenGL textured index batch builder")
    require(opengl_presenter, "private int copyTexturedIndicesInLegacyOrder(Renderer3DMeshFrame meshFrame, int indexCount)", "OpenGL legacy-ordered textured index builder")
    require(opengl_presenter, "Collections.sort(orderedTriangles", "OpenGL legacy draw-order sort")
    require(opengl_presenter, "legacyDrawOrderOrEnd(triangleLegacyDrawOrders", "OpenGL missing legacy order fallback")
    require(opengl_presenter, "private boolean isTexturedDiagnosticTriangle(Renderer3DModelKind[] triangleModelKinds, int triangle)", "OpenGL textured diagnostic kind filter")
    require(opengl_presenter, "modelKind == Renderer3DModelKind.TERRAIN", "OpenGL textured diagnostic terrain default")
    require(opengl_presenter, "WORLD_MESH_TEXTURED_STATIC_VISIBLE", "OpenGL textured diagnostic static opt-in")
    require(opengl_presenter, "private void drawWorldSprites(Frame frame)", "OpenGL world sprite diagnostic draw")
    require(opengl_presenter, "private WorldSpriteMatch[] matchWorldSpriteAnchors(", "OpenGL world sprite anchor matcher")
    require(opengl_presenter, "command.getLegacySpriteId() != anchor.getSpriteId()", "OpenGL world sprite exact id match")
    require(opengl_presenter, "gl.glVertex3f(topX0, y0, z);", "OpenGL world sprite depth vertex")
    require(opengl_presenter, "private static final class WorldSpriteMatch", "OpenGL world sprite match class")
    require(opengl_presenter, "private static final class WorldMeshTextureBatch", "OpenGL world texture batch class")
    require(opengl_presenter, "new LinkedHashMap<>()", "OpenGL texture batch deterministic grouping")
    require(opengl_presenter, "meshFrame.getCenterX() + vertices[sourceOffset + Renderer3DMeshFrame.SCREEN_X_OFFSET]", "OpenGL centered mesh x upload")
    require(opengl_presenter, "meshFrame.getCenterY() + vertices[sourceOffset + Renderer3DMeshFrame.SCREEN_Y_OFFSET]", "OpenGL centered mesh y upload")
    require(opengl_presenter, "-vertices[sourceOffset + Renderer3DMeshFrame.CAMERA_Z_OFFSET]", "OpenGL mesh depth direction matches software depth")
    require(opengl_presenter, "Renderer3DMeshFrame.TEXTURE_U_OFFSET", "OpenGL mesh texture u upload")
    require(opengl_presenter, "Renderer3DMeshFrame.TEXTURE_V_OFFSET", "OpenGL mesh texture v upload")
    require(opengl_presenter, "Renderer3DMeshFrame.TEXTURE_RED_OFFSET", "OpenGL mesh texture light upload")
    require(opengl_presenter, "private void drawTexturedDiagnostic()", "OpenGL textured diagnostic draw")
    require(opengl_presenter, "gl.glTexCoordPointer(", "OpenGL texture coordinate pointer")
    require(opengl_presenter, "gl.glEnableClientState(gl.GL_TEXTURE_COORD_ARRAY);", "OpenGL texture coordinate array enable")
    require(opengl_presenter, "batch.startIndex * 4L", "OpenGL batched texture index offset")
    require(opengl_presenter, "gl.glEnable(gl.GL_DEPTH_TEST);", "OpenGL mesh depth enable")
    require(opengl_presenter, "gl.glClear(gl.GL_DEPTH_BUFFER_BIT);", "OpenGL mesh depth clear")
    require(opengl_presenter, "gl.glPolygonMode(gl.GL_FRONT_AND_BACK, gl.GL_LINE);", "OpenGL visible mesh wireframe mode")
    require(opengl_presenter, "gl.glColor4f(0.1f, 0.85f, 1.0f, 0.35f);", "OpenGL visible mesh translucent diagnostic color")
    require(opengl_presenter, "gl.glPolygonMode(gl.GL_FRONT_AND_BACK, gl.GL_FILL);", "OpenGL visible mesh polygon mode restore")
    require(opengl_presenter, "gl.glDrawElements(gl.GL_TRIANGLES, indexCount, gl.GL_UNSIGNED_INT, 0L);", "OpenGL indexed mesh draw")
    require(opengl_presenter, "RenderTelemetry.recordOpenGLWorldMeshFrame(vertexCount, indexCount, indexCount / 3);", "OpenGL mesh telemetry call")
    require(opengl_presenter, "if (!wireframeVisible && !texturedVisible) {", "OpenGL mesh upload-only path")
    require(opengl_presenter, "gl.glDisable(gl.GL_DEPTH_TEST);\n\t\tgl.glDisable(gl.GL_SCISSOR_TEST);\n\t\tgl.glDisable(gl.GL_BLEND);", "base framebuffer GL state reset")
    upload_only_block = opengl_presenter.split("if (!wireframeVisible && !texturedVisible) {", 1)[1].split("}\n\n\t\t\tgl.glEnable(gl.GL_DEPTH_TEST);", 1)[0]
    if "gl.glDisable(gl.GL_TEXTURE_2D)" in upload_only_block or "gl.glEnable(gl.GL_DEPTH_TEST)" in upload_only_block:
        raise AssertionError("OpenGL mesh upload-only path must not mutate visible GL texture/depth state")
    require(opengl_presenter, "glBufferDataFloat = method(gl15Class, \"glBufferData\", int.class, FloatBuffer.class, int.class);", "LWJGL float buffer binding")
    require(opengl_presenter, "glPushAttrib = method(gl11Class, \"glPushAttrib\", int.class);", "LWJGL pass server-state binding")
    require(opengl_presenter, "glPushClientAttrib = method(gl11Class, \"glPushClientAttrib\", int.class);", "LWJGL pass client-state binding")
    require(opengl_presenter, "glPolygonMode = method(gl11Class, \"glPolygonMode\", int.class, int.class);", "LWJGL polygon mode binding")
    require(opengl_presenter, "glTexCoordPointer = method(gl11Class, \"glTexCoordPointer\", int.class, int.class, int.class, long.class);", "LWJGL texture coordinate pointer binding")
    require(opengl_presenter, "glVertex3f = method(gl11Class, \"glVertex3f\", float.class, float.class, float.class);", "LWJGL 3D vertex binding")
    require(opengl_presenter, "GL_TEXTURE_COORD_ARRAY = constant(gl11Class, \"GL_TEXTURE_COORD_ARRAY\");", "LWJGL texture coordinate array binding")

    require(plan, "No red back-face flash when walking past `tinrock1` ore rocks.", "tin rock validation checklist")
    require(plan, "SPOILED_MILK_RENDERER3D_GEOMETRY_CAPTURE=true", "geometry capture plan flag")
    require(plan, "SPOILED_MILK_RENDERER3D_VISIBLE_WORLD=true", "visible world plan flag")
    require(plan, "SPOILED_MILK_OPENGL_WORLD_MESH=true", "OpenGL world mesh plan flag")
    require(plan, "SPOILED_MILK_OPENGL_WORLD_MESH_VISIBLE=true", "visible OpenGL world mesh plan flag")
    require(plan, "SPOILED_MILK_OPENGL_WORLD_TEXTURED_VISIBLE=true", "visible textured OpenGL world plan flag")
    require(plan, "SPOILED_MILK_OPENGL_WORLD_TEXTURED_STATIC_VISIBLE=true", "visible textured static OpenGL world plan flag")
    require(plan, "SPOILED_MILK_OPENGL_WORLD_STATIC_TEXTURES=true|false", "OpenGL static texture sampling plan flag")
    require(plan, "SPOILED_MILK_OPENGL_WORLD_TEXTURED_ALPHA=0.0..1.0", "OpenGL textured alpha plan flag")
    require(plan, "SPOILED_MILK_OPENGL_WORLD_REPLACEMENT_COMPOSITE=true|false", "OpenGL world replacement composite plan flag")
    require(plan, "SPOILED_MILK_OPENGL_WORLD_SPRITES_VISIBLE=true", "visible OpenGL world sprite plan flag")
    require(plan, "Classify captured world geometry as terrain, wall, roof, game object,", "typed geometry plan item")
    require(plan, "Render captured terrain, wall, game-object, and wall-object faces into", "depth buffer plan item")
    require(plan, "visible renderer-v2 world backend", "visible world plan item")
    require(plan, "OpenGL World Backend", "GPU world backend plan section")
    require(plan, "Map typed renderer-v2 geometry commands into a CPU-side GPU-ready", "mesh buffer plan item")
    require(plan, "Upload captured world geometry through an opt-in OpenGL VBO/EBO", "OpenGL mesh upload plan item")
    require(plan, "Isolate OpenGL upload, framebuffer, world, and sprite passes", "OpenGL pass isolation plan item")
    require(plan, "Draw the visible OpenGL world mesh diagnostic as a translucent", "OpenGL wireframe diagnostic plan item")
    require(plan, "Carry per-triangle texture id, fallback color, model kind,", "mesh material metadata plan item")
    require(plan, "Capture legacy world texture palette/index data as immutable", "renderer-v2 texture data plan item")
    require(plan, "Derive normalized face-basis texture coordinates from captured", "renderer-v2 texture coordinate plan item")
    require(plan, "Upload referenced renderer-v2 world textures into an OpenGL atlas", "OpenGL world texture atlas plan item")
    require(plan, "Add an opt-in textured OpenGL world diagnostic", "OpenGL textured diagnostic plan item")
    require(plan, "Capture the final legacy sorted draw order for visible static world", "legacy sorted draw-order plan item")
    require(plan, "Capture the final near-plane clipped camera/projected vertices", "near-plane clipped geometry plan item")
    require(plan, "Preserve captured legacy draw order for textured static OpenGL", "legacy-ordered static OpenGL plan item")
    require(plan, "Render flat-colored static world triangles in the same legacy-ordered", "OpenGL flat static world plan item")
    require(plan, "Add an OpenGL world replacement composite mode", "OpenGL replacement composite plan item")
    require(plan, "Pad OpenGL texture-atlas uploads with duplicated border texels", "OpenGL atlas padding plan item")
    require(plan, "Add a conservative projected-triangle sanity guard", "OpenGL projected triangle guard plan item")
    require(plan, "Capture legacy per-render-vertex light/fog intensity", "OpenGL texture light modulation plan item")
    require(plan, "Add a flat material-color fallback for texture-backed walls", "OpenGL static texture fallback plan item")
    require(plan, "Use average opaque texture color as the flat material fallback", "OpenGL static texture average fallback plan item")
    require(plan, "SPOILED_MILK_OPENGL_WORLD_STATIC_TEXTURES", "OpenGL static texture switch plan item")
    require(plan, "Route exact-ID replacement-composite scene/entity sprites through captured", "OpenGL replacement anchored sprite plan item")
    require(plan, "software-visible pixels so composite humanoid sprites", "OpenGL replacement visible scene sprite plan item")
    require(plan, "Capture projected legacy sprite depth anchors from the final sorted draw", "sprite depth anchor plan item")
    require(plan, "Extend the textured diagnostic to static geometry now that sprite depth", "OpenGL textured static diagnostic follow-up")
    require(plan, "Build an opt-in OpenGL world-sprite diagnostic batch from captured depth", "OpenGL sprite world batch plan item")
    require(plan, "Promote the OpenGL world-sprite batch from translucent diagnostic overlay", "OpenGL sprite source-of-truth follow-up")
    require(plan, "Options and Quality Settings Cleanup", "future user-facing options plan section")

    print("PASS: renderer-v2 world geometry capture and tinrock normalization are wired")


if __name__ == "__main__":
    main()
